[project]
name = "aibricks"
version = "3.1.0"
description = "Simple, unified interface to multiple Generative AI providers."
license = { text = "MIT License" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
